### ISSUE TITLE
Captive portal : User is getting parsing error on the mobile device when clicked on download apk

### ISSUE THREAD

**Issue by RedmineQualitrix** [projectOpenRAP/OpenRAP#24] opened 2017-11-27 10:13 UTC
Steps to reproduce : 
1.Connect to the CDN network.
2.Login as admin.
3.Go to captive portal page.
4.Provide the logo and other details and apk as well.
5.Click on update captive portal.
6.Open the mobile browser and type google.com.
7.Try to download the apk.
8.Observe it shows an error message as "There was a problem while parsing the package"

Refer the attached video:

[20171127_145435.zip](https://github.com/projectOpenRAP/OpenRAP/files/1505391/20171127_145435.zip)

**Comment by chetansk** [comment] 2017-11-27 11:23
Duplicate of issue #19

**Closed by chetansk** 2017-11-27 11:23 UTC
Labels: duplicate
