### ISSUE TITLE
CDN: The date of data specified inside telemetry folder is wrong 

### ISSUE THREAD

**Issue by RedmineQualitrix** [projectOpenRAP/OpenRAP#52] opened 2017-12-19 11:59 UTC
1.Connect the Pc to the CDN device 
2.Open the URL (admin.edgecdn.com:8008/).
3.Click on USB download.
4.Open the pen drive and open the telemetry folder.
5. Observe that the date of data specified inside telemetry folder is wrong

Expected result:
It should display current date.

Actual result:
It is not displaying current date.

Refer the video attached:

[Telemetryissue.zip](https://github.com/projectOpenRAP/OpenRAP/files/1571554/Telemetryissue.zip)

**Comment by siddharthmunot** [comment] 2017-12-22 05:17
Since the device doesn't have a clock, the time wont be updated and this is just the date of the .zip files, JSON data inside the files has the correct date, which will be consumed by the cloud.

**Comment by siddharthmunot** [comment] 2017-12-22 05:17
So with this respect marking this as not a bug but hardware limitation.

**Closed by siddharthmunot** 2017-12-22 05:17 UTC
